version: '3.9'
services:
    postgres:
        image: postgres:latest
        container_name: PG-COSTYRION
        networks:
          - default
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=costyrion
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        command:
          - "postgres"
          - "-c"
          - "shared_preload_libraries=pg_stat_statements"
        volumes: 
          - ${HOME}/Postgres/COSTYRION:/var/lib/postgresql/data
          # - ${HOME}/Postgres/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql

networks:
    default:
        name: pgn-costyrion