CREATE TABLE xdb.key_type
(
    ktp_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ktp_name VARCHAR(40)
);

CREATE TABLE xdb.key_definition
(
    kdf_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ktp_id INT NOT NULL,
    kdf_name VARCHAR(40),
);

CREATE TABLE xdb.cost_center
(
    cct_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- kdf_id INT NOT NULL,
    cct_code VARCHAR(10) DEFAULT (uuid_generate_v4()) NOT NULL,
    cct_name VARCHAR(255) NOT NULL,
    cct_group VARCHAR(40) NOT NULL,
    cct_type VARCHAR(20) NOT NULL,
    cct_level SMALLINT NOT NULL,
    cct_balance_code VARCHAR(20),
    cct_balance_name VARCHAR(255),
);

CREATE TABLE xdb.key_map
(
    kmp_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- kdf_id INT NOT NULL,
    cct_id_source INT,
    cct_id_target INT,
    -- FOREIGN KEY (cct_id_source) REFERENCES xdb.cost_center (cct_id),
    -- FOREIGN KEY (cct_id_target) REFERENCES xdb.cost_center (cct_id),
    -- FOREIGN KEY (kdf_id) REFERENCES xdb.key_definition (kdf_id)
);

CREATE TABLE xdb.account
(
    acc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- cct_id INT NOT NULL,
    acc_code VARCHAR(20) NOT NULL,
    acc_code_cost VARCHAR(20) NOT NULL,
    acc_group CHAR(1) NOT NULL,
    acc_balance VARCHAR(255),
    acc_code_level_01 VARCHAR(20),
    acc_code_level_02 VARCHAR(20),
    acc_code_level_03 VARCHAR(20),
    acc_name_level_01 VARCHAR(233),
    acc_name_level_02 VARCHAR(233),
    acc_name_level_03 VARCHAR(233),
    acc_desc_level_01 VARCHAR(255),
    acc_desc_level_02 VARCHAR(255),
    acc_desc_level_03 VARCHAR(255),
    acc_balance_code VARCHAR(20),
);

CREATE TABLE xdb.budget
(
    bdg_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- acc_id INT NOT NULL,
    bdg_date DATE NOT NULL,
    bdg_value DECIMAL(15,2) NOT NULL,
);

CREATE TABLE xdb.journal_entry
(
    jen_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- acc_id INT NOT NULL,
    jen_date DATE NOT NULL,
    jen_type VARCHAR(2) NOT NULL,
    jen_value DECIMAL(15,2) NOT NULL,
);

CREATE TABLE xdb.journal_entry_calculated
(
    jec_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acc_id INT NOT NULL,
    cct_id INT NOT NULL,
    jec_date DATE NOT NULL,
    jec_type VARCHAR(2) NOT NULL,
    jec_value DECIMAL(15,2) NOT NULL,
    -- FOREIGN KEY (acc_id) REFERENCES xdb.account (acc_id),
    -- FOREIGN KEY (cct_id) REFERENCES xdb.cost_center (cct_id)
);

CREATE TABLE xdb.key_source_data
(
    ksd_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ktp_id INT NOT NULL,
    cct_id INT NOT NULL,
    ksd_date_from DATE NOT NULL,
    ksd_date_to DATE NOT NULL,
    ksd_value DECIMAL(15,2) NOT NULL,
    -- FOREIGN KEY (cct_id) REFERENCES xdb.cost_center (cct_id),
    -- FOREIGN KEY (ktp_id) REFERENCES xdb.key_type (ktp_id)
);

CREATE TABLE xdb.key_value
(
    kvl_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kmp_id INT NOT NULL,
    kdf_id INT NOT NULL,
    ktp_id INT NOT NULL,
    cct_id_source INT NOT NULL,
    cct_id_target INT NOT NULL,
    kvl_date_from DATE NOT NULL,
    kvl_date_to DATE NOT NULL,
    kvl_value DECIMAL(15,4) NOT NULL,
    FOREIGN KEY (cct_id_source) REFERENCES xdb.cost_center (cct_id),
    FOREIGN KEY (cct_id_target) REFERENCES xdb.cost_center (cct_id),
    FOREIGN KEY (kdf_id) REFERENCES xdb.key_definition (kdf_id),
    FOREIGN KEY (kmp_id) REFERENCES xdb.key_map (kmp_id),
    FOREIGN KEY (ktp_id) REFERENCES xdb.key_type (ktp_id)
);